---
title: "11_HI_anova_models"
author: "Jake Cavaiani"
date: "9/13/2022"
output:
  word_document: default
  html_document: default
---

#load libraries 
```{r}
library(here)
library(tidyverse)
library(nlme)
library(forecast)
library(stats)
library(readr)
library(ggplot2)
library(plotly)
library(GGally)
library(ggpmisc)
library(ggpubr)
library(ggExtra)
library(lubridate)
library(lme4)
library(MuMIn)
library(multcomp)
```

# load in the data 
```{r}
AMC <- read.csv(here("Output_from_analysis", "07_Combine_HI_BETA_FI", "antecedent_HI_FI_AllYears.csv"))

AMC <- AMC[c("Hyst_index","site.ID", "storm.ID", "response_var", "Flush_index", "month.y", "day.y", "year", "Beta_index", "doy", "burn", "pf", "date")] # selecting the columns that I want

colNames <- c("Hyst_index", "site.ID", "storm.ID", "response_var", "Flush_index", "month", "day", "year", "Beta_index", "doy", "burn", "pf", "date")

names(AMC)<- colNames # renaming columns 

AMC <- AMC %>% 
  group_by(site.ID, response_var, year) %>% 
  dplyr::summarise(meanHI = mean(Hyst_index, na.rm = TRUE),
                   meanBETA = mean(Beta_index, na.rm = TRUE),
                   sdHI = sd(Hyst_index, na.rm = TRUE),
                   sdBETA = sd(Beta_index, na.rm = TRUE),
                   CVhi = sdHI/meanHI,
                   CVbeta = sdBETA/meanBETA,
                   response_var = paste(response_var),
                   Date = as.Date(date),
                   DOY = as.numeric(doy),
                   burn = paste(burn),
                   PF = paste(pf))

AMC <- AMC[!duplicated(AMC$meanHI), ] # removing duplicated rows 

AMC$year <- as.character(AMC$year)
##subsetting by solute 
# NO3 #
HI_FI_NO3 = subset(AMC, response_var == "NO3")
# fDOM #
HI_FI_fDOM = subset(AMC, response_var == "fDOM")
# SPC #
HI_FI_SPC = subset(AMC, response_var == "SPC")
# turb #
HI_FI_turb = subset(AMC, response_var == "turb")


```


# plot 
```{r}
ggplot(AMC, aes(site.ID, meanHI, fill = site.ID)) +
  geom_boxplot() +
  facet_wrap(~response_var, scales = "free") +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("HI_all_solutes.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)
```


### HI ###
```{r}
#NO3
ggplot(HI_FI_NO3, aes(site.ID, meanHI, fill = site.ID)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("HI_NO3.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

NO3.CV.HI.mod <- lmer(meanHI ~ site.ID + (1|year), data = HI_FI_NO3)

plot(NO3.CV.HI.mod)
qqnorm(resid(NO3.CV.HI.mod))
summary(NO3.CV.HI.mod)

emmeans(NO3.CV.HI.mod, list(pairwise ~ site.ID), adjust = "tukey")
# add post hoc pairwise comparisons
```
 
#fDOM 

```{r}
#fDOM
ggplot(HI_FI_fDOM, aes(site.ID, meanHI, fill = site.ID)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("HI_fDOM.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

fDOM.CV.HI.mod <- lmer(meanHI ~ site.ID + (1|year), data = HI_FI_fDOM)

plot(fDOM.CV.HI.mod)
qqnorm(resid(fDOM.CV.HI.mod))
summary(fDOM.CV.HI.mod)

emmeans(fDOM.CV.HI.mod, list(pairwise ~ site.ID), adjust = "tukey")
# add post hoc pairwise comparisons

```
normality looks good 


```{r}
#SPC
ggplot(HI_FI_SPC, aes(site.ID, meanHI, fill = site.ID)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("HI_SPC.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

SPC.CV.HI.mod <- lmer(meanHI ~ site.ID + (1|year), data = HI_FI_SPC)

plot(SPC.CV.HI.mod)
qqnorm(resid(SPC.CV.HI.mod))
summary(SPC.CV.HI.mod)

emmeans(SPC.CV.HI.mod, list(pairwise ~ site.ID), adjust = "tukey")
# add post hoc pairwise comparisons

```
non-normal....lets try to do a log transformation 


```{r}
#turb
ggplot(HI_FI_turb, aes(site.ID, meanHI, fill = site.ID)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("HI_turb.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

turb.CV.HI.mod <- lmer(meanHI ~ site.ID + (1|year), data = HI_FI_turb)

plot(turb.CV.HI.mod)
qqnorm(resid(turb.CV.HI.mod))
summary(turb.CV.HI.mod)

emmeans(turb.CV.HI.mod, list(pairwise ~ site.ID), adjust = "tukey")
# add post hoc pairwise comparisons

```

### BETA ###

```{r}
ggplot(AMC, aes(site.ID, meanBETA, fill = site.ID)) +
  geom_boxplot() +
  facet_wrap(~response_var, scales = "free") +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("BETA_all_solutes.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

```

```{r}
#NO3
ggplot(HI_FI_NO3, aes(site.ID, meanBETA, fill = site.ID)) +
  geom_boxplot() +
  facet_wrap(~response_var, scales = "free") +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("BETA_NO3.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

NO3.CV.BETA.mod <- lmer(meanBETA ~ site.ID + (1|year), data = HI_FI_NO3)

plot(NO3.CV.BETA.mod)
qqnorm(resid(NO3.CV.BETA.mod))
summary(NO3.CV.BETA.mod)

emmeans(NO3.CV.BETA.mod, list(pairwise ~ site.ID), adjust = "tukey")
# add post hoc pairwise comparisons
```

```{r}
summary(NO3) # nothing is significant 
summary.lm(NO3)

```

#fDOM
```{r}
ggplot(HI_FI_fDOM, aes(site.ID, meanBETA, fill = site.ID)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("BETA_fDOM.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

fDOM.CV.BETA.mod <- lmer(meanBETA ~ site.ID + (1|year), data = HI_FI_fDOM)

plot(fDOM.CV.BETA.mod)
qqnorm(resid(fDOM.CV.BETA.mod))
summary(fDOM.CV.BETA.mod)

emmeans(fDOM.CV.BETA.mod, list(pairwise ~ site.ID), adjust = "tukey")
# add post hoc pairwise comparisons

```

```{r}
#SPC
ggplot(HI_FI_SPC, aes(site.ID, meanBETA, color = site.ID, shape = as.character(year))) +
  geom_point() +
  scale_color_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("BETA_SPC_year.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

SPC.CV.BETA.mod <- lmer(meanBETA ~ site.ID + (1|year), data = HI_FI_SPC)

plot(SPC.CV.BETA.mod)
qqnorm(resid(SPC.CV.BETA.mod))
summary(SPC.CV.BETA.mod)

emmeans(SPC.CV.BETA.mod, list(pairwise ~ site.ID), adjust = "tukey")
# add post hoc pairwise comparisons

```

```{r}
#turb
ggplot(HI_FI_turb, aes(site.ID, meanBETA, fill = site.ID)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("BETA_turb.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

turb.CV.BETA.mod <- lmer(meanBETA ~ site.ID + (1|year), data = HI_FI_turb)

plot(turb.CV.BETA.mod)
qqnorm(resid(turb.CV.BETA.mod))
summary(turb.CV.BETA.mod)

emmeans(turb.CV.BETA.mod, list(pairwise ~ site.ID), adjust = "tukey")
```

### SDs of storm metrics ###

```{r}
#plot 
ggplot(AMC, aes(site.ID, sdHI, fill = site.ID)) +
  geom_boxplot() +
  facet_wrap(~response_var, scales = "free") +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("sdHI_all_solutes.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)


HI_FI_NO3$logSDhi <- log(abs(HI_FI_NO3$sdHI))
HI_FI_fDOM$logSDhi <- log(abs(HI_FI_fDOM$sdHI))
HI_FI_SPC$logSDhi <- log(abs(HI_FI_SPC$sdHI))
HI_FI_turb$logSDhi <- log(abs(HI_FI_turb$sdHI))

HI_FI_NO3$logSDbeta <- log(abs(HI_FI_NO3$sdBETA))
HI_FI_fDOM$logSDbeta <- log(abs(HI_FI_fDOM$sdBETA))
HI_FI_SPC$logSDbeta <- log(abs(HI_FI_SPC$sdBETA))
HI_FI_turb$logSDbeta <- log(abs(HI_FI_turb$sdBETA))

```

# HI #
# NO3-
```{r}
ggplot(HI_FI_NO3, aes(site.ID, sdHI, fill = site.ID)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("sdHI_NO3.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

NO3.CV.sdHI.mod <- lmer(sdHI ~ site.ID + (1|year), data = HI_FI_NO3)

plot(NO3.CV.sdHI.mod)
qqnorm(resid(NO3.CV.sdHI.mod))
summary(NO3.CV.sdHI.mod)

emmeans(NO3.CV.sdHI.mod, list(pairwise ~ site.ID), adjust = "tukey")
```

```{r}
ggplot(HI_FI_fDOM, aes(site.ID, sdHI, fill = site.ID)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("sdHI_fDOM.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

fDOM.CV.sdHI.mod <- lmer(sdHI ~ site.ID + (1|year), data = HI_FI_fDOM)

plot(fDOM.CV.sdHI.mod)
qqnorm(resid(fDOM.CV.sdHI.mod))
summary(fDOM.CV.sdHI.mod)

emmeans(fDOM.CV.sdHI.mod, list(pairwise ~ site.ID), adjust = "tukey")
```

# SPC
```{r}
ggplot(HI_FI_SPC, aes(site.ID, sdHI, fill = site.ID)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("sdHI_SPC.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

SPC.CV.sdHI.mod <- lmer(sdHI ~ site.ID + (1|year), data = HI_FI_SPC)

plot(SPC.CV.sdHI.mod)
qqnorm(resid(SPC.CV.sdHI.mod))
summary(SPC.CV.sdHI.mod)

emmeans(SPC.CV.sdHI.mod, list(pairwise ~ site.ID), adjust = "tukey")
```

# turb
```{r}
ggplot(HI_FI_turb, aes(site.ID, sdHI, fill = site.ID)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("sdHI_Turb.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

ggplot(HI_FI_turb, aes(site.ID, sdHI, color = site.ID, shape = as.character(year))) +
  geom_point() +
  scale_color_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("sdHI_Turb_year.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)

turb.CV.sdHI.mod <- lmer(sdHI ~ site.ID + (1|year), data = HI_FI_turb)

plot(turb.CV.sdHI.mod)
qqnorm(resid(turb.CV.sdHI.mod))
summary(turb.CV.sdHI.mod)

emmeans(turb.CV.sdHI.mod, list(pairwise ~ site.ID), adjust = "tukey")

```
# BETA 
```{r}
#plot 
ggplot(AMC, aes(site.ID, sdBETA, fill = site.ID)) +
  geom_boxplot() +
  facet_wrap(~response_var, scales = "free") +
  scale_fill_manual(values = c("#3288BD", "#FF7F00","#A6761D", "#6A3D9A", "#66C2A5", "#E7298A")) +
  theme_classic()

ggsave("sdBETA_all_solutes.pdf",
       path = here("plots", "Storm_metrics_sites"),
       width = 10, height = 10)


```

# NO3
```{r}
NO3.CV.sdBETA.mod <- lmer(sdBETA ~ site.ID + (1|year), data = HI_FI_NO3)

plot(NO3.CV.sdBETA.mod)
qqnorm(resid(NO3.CV.sdBETA.mod))
summary(NO3.CV.sdBETA.mod)

emmeans(NO3.CV.sdBETA.mod, list(pairwise ~ site.ID), adjust = "tukey")
```

# fDOM
```{r}
fDOM.CV.sdBETA.mod <- lmer(sdBETA ~ site.ID + (1|year), data = HI_FI_fDOM)

plot(fDOM.CV.sdBETA.mod)
qqnorm(resid(fDOM.CV.sdBETA.mod))
summary(fDOM.CV.sdBETA.mod)

emmeans(fDOM.CV.sdBETA.mod, list(pairwise ~ site.ID), adjust = "tukey")
```

# SPC
```{r}
SPC.CV.sdBETA.mod <- lmer(sdBETA ~ site.ID + (1|year), data = HI_FI_SPC)

plot(SPC.CV.sdBETA.mod)
qqnorm(resid(SPC.CV.sdBETA.mod))
summary(SPC.CV.sdBETA.mod)

emmeans(SPC.CV.sdBETA.mod, list(pairwise ~ site.ID), adjust = "tukey")
```
# turb 
```{r}
turb.CV.sdBETA.mod <- lmer(sdBETA ~ site.ID + (1|year), data = HI_FI_turb)

plot(turb.CV.sdBETA.mod)
qqnorm(resid(turb.CV.sdBETA.mod))
summary(turb.CV.sdBETA.mod)

emmeans(turb.CV.sdBETA.mod, list(pairwise ~ site.ID), adjust = "tukey")
```


