---
title: "18_Publication_plotting_roundup"
output: html_document
date: "2023-11-21"
editor_options: 
  chunk_output_type: console
---

```{r - libraries}
library(ggplot2)
library(ggnewscale)
library(here)
library(lubridate)
library(tidyverse)
library(ggpattern)
library(ggsignif)
library(tidyquant)
library(ggpubr)
library(extrafont)
```

### Time series daily stream concentration by year: 10_gls_models for TKH 4/12/2024 ###
```{r}
# 10_gls_models plotting ####
mean_daily <- read.csv(here("Output_from_analysis", "08_Catchment_characteristics", "mean_daily.csv"))

mean_daily$datetimeAK <- ymd(mean_daily$day)
mean_daily <- mean_daily[order(mean_daily$year, mean_daily$site.ID), ]

mean_daily$year <- as.character(mean_daily$year)

mean_daily$Burn <- NA

mean_daily <- mean_daily %>% 
  mutate(across(c(Burn),
                ~ifelse(site.ID == "CARI" | site.ID == "FRCH" | site.ID == "VAUL", "unburned", "burned")))

mean_daily$PF <- NA

mean_daily <- mean_daily %>% 
  mutate(across(c(PF),
                ~ifelse(site.ID == "VAUL" | site.ID == "STRT", "High", "Moderate")))


vn = expression(paste(N*O[3]^"-"))
# mean concentration across years for each site 
mean_daily_site <- mean_daily %>% 
  group_by(site.ID) %>% 
  dplyr::summarise(meanNO3 = mean(dailyNO3, na.rm = TRUE),
                   meanfDOM = mean(dailyfDOM, na.rm = TRUE),
                   meanSPC = mean(dailySPC, na.rm = TRUE),
                   meanTurb = mean(dailyTurb, na.rm = TRUE))


mean_daily_long <- mean_daily %>%
  pivot_longer(
    cols = starts_with("daily"),
    names_to = "response_var",
    names_prefix = "wk",
    values_to = "concentration") # converting to a long format so each response_var is within a single column


mean_daily_long$response_var <- factor(mean_daily_long$response_var, levels = c("dailyfDOM", "dailyNO3", "dailySPC", "dailyTurb", "dailyABS"), 
                  labels = c("fDOM (QSU)", "NO3- (µM)", "SPC(µS/cm)", "Turbidity (FNU)", "ABS @ 254nm"))


# Plotting #
mean_daily_long %>% 
  filter(!year == 2015) %>% 
ggplot(aes(x = datetimeAK, y = concentration, color = site.ID)) +
  geom_line() +
  scale_color_manual(values = c("#3288BD","#FF7F00", "#A6761D", "#6A3D9A", "#66C2A5", "#E7298A"), 
                     guide = guide_legend(title = "Site")) +
  xlab("") +
  ylab("") +
  facet_grid(response_var~year, scales = "free") +
  theme_classic() +
  theme(strip.text = element_text(size = 14),
        axis.text.x = element_text(size = 13),
        axis.title.x = element_text(size = 20),
        axis.text.y = element_text(size = 20))

ggsave("DoD_2018_2022.pdf",
       path = here("plots", "Chems_year"),
       width = 10, height = 8, units = "in")


```


### daily stream concentration by year: 10_gls_models ###
```{r - load in data}
mean_daily <- read.csv(here("Output_from_analysis", "08_Catchment_characteristics", "mean_daily.csv"))

mean_daily$datetimeAK <- ymd(mean_daily$day)
mean_daily <- mean_daily[order(mean_daily$year, mean_daily$site.ID), ]

mean_daily$year <- as.character(mean_daily$year)

mean_daily$Burn <- NA

mean_daily <- mean_daily %>% 
  mutate(across(c(Burn),
                ~ifelse(site.ID == "CARI" | site.ID == "FRCH" | site.ID == "VAUL", "unburned", "burned")))

mean_daily$PF <- NA

mean_daily <- mean_daily %>% 
  mutate(across(c(PF),
                ~ifelse(site.ID == "VAUL" | site.ID == "MOOS", "High", "Low")))


vn = expression(paste(N*O[3]^"-"))
# mean concentration across years for each site 
mean_daily_site <- mean_daily %>% 
  group_by(site.ID) %>% 
  dplyr::summarise(meanNO3 = mean(dailyNO3, na.rm = TRUE),
                   meanfDOM = mean(dailyfDOM, na.rm = TRUE),
                   meanSPC = mean(dailySPC, na.rm = TRUE),
                   meanTurb = mean(dailyTurb, na.rm = TRUE))

```

### PLOTTING ####
```{r - NO3}
vn = expression(paste(N*O[3]^"-"*(μM)))

mean_daily_new <- mean_daily
mean_daily_new$site.ID <- factor(mean_daily_new$site.ID,     # Reorder factor levels
                         c("CARI", "FRCH", "VAUL", "MOOS", "POKE", "STRT"))


# all years  #
# POKE - 25%
# CARI - 29%
# STRT - 30%
# FRCH - 33%
# MOOS - 38%
# VAUL - 58%
desired_order <- c("POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL")

# with letters # 
annotations <- data.frame(
  year = c("2015", "2015",
           "2018", "2018", "2018", 
           "2019", "2019", "2019", "2019", "2019", "2019",
           "2020", "2020", "2020", "2020", "2020", "2020",
           "2021", "2021", "2021", "2021", "2021", "2021",
           "2022", "2022", "2022", "2022", "2022", "2022"),
  site.ID = c("FRCH", "MOOS",
              "CARI",  "FRCH", "MOOS",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL"),
  Label = c("", "", 
            "", "", "", 
            "", "", "", "", "", "", 
            "a", "a", "ab", "a", "b", "c", 
            "ab", "b", "a", "a", "ab", "ab", 
            "a", "ac", "bc", "ac", "b", "b"),
  y_position = c(50, 50, 
                 50, 50, 50, 
                 50, 50, 50, 50, 50, 50,
                 45, 45, 45, 45, 45, 45,
                 45, 45, 45, 45, 45, 45,
                 45, 45, 45, 45, 45, 45),
  Burn = c("unburned", "burned",
           "unburned", "unburned", "burned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned"))

ggplot(mean_daily_new, aes(x = site.ID, y = dailyNO3, pattern = Burn, fill = site.ID)) +
        ggdist::stat_halfeye(adjust = 0.5, 
                       justification = -.3,
                       .width = -0,
                       point_colour = NA,
                       scale = 0.5) +
  geom_boxplot(width = .25,
                 outlier.colour = NA,
                 alpha = 0.5) +
   geom_boxplot_pattern(position = position_dodge(preserve = "single"), 
                        width = .25,
                        color = "black", 
                        pattern_fill = "white", 
                        pattern_angle = 45, 
                        pattern_density = 0.1, 
                        pattern_spacing = 0.025, 
                        pattern_key_scale_factor = 0.6) +
  scale_pattern_manual(values = c(burned = "stripe", unburned = "none")) +
  scale_x_discrete(limits = desired_order,
                   labels = c("POKE" = "POKE\n(25%)",
                              "CARI" = "CARI\n(29%)",
                              "STRT" = "STRT\n(30%)",
                              "FRCH" = "FRCH\n(33%)",
                              "MOOS" = "MOOS\n(38%)",
                              "VAUL" = "VAUL\n(58%)")) +
  coord_cartesian(xlim = c(1, 6.05)) +
  
  scale_fill_manual(values=c("#3288BD","#FF7F00", "#E7298A", "#A6761D", "#6A3D9A", "#66C2A5"), guide = "none") +
  facet_wrap(~year) +
  geom_text(data = annotations, aes(label = Label, y = y_position), 
            position = position_dodge(width = 0.75), size = 8) +
  theme_tq() +
  theme(axis.text.x = element_text(size = 16),
        axis.title.y = element_text(size = 25),
        axis.text.y = element_text(size = 20),
        strip.text = element_text(size = 20), 
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20)) +
  labs(x= "", y = vn) 

ggsave("NO3_facet_year_3.pdf",
       path = here("plots", "Publication"),
       width = 15, height = 12)

grDevices::cairo_pdf("NO3_facet_year_3.pdf")

cairo

```

```{r - DOC}
# all years  #
# POKE - 25%
# CARI - 29%
# STRT - 30%
# FRCH - 33%
# MOOS - 38%
# VAUL - 58%
desired_order <- c("POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL")

# with letters # 
annotations <- data.frame(
  year = c("2015", "2015",
           "2018", "2018", "2018", 
           "2019", "2019", "2019", "2019", "2019", "2019",
           "2020", "2020", "2020", "2020", "2020", "2020",
           "2021", "2021", "2021", "2021", "2021", "2021",
           "2022", "2022", "2022", "2022", "2022", "2022"),
  site.ID = c("FRCH", "MOOS",
              "CARI",  "FRCH", "MOOS",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL"),
  Label = c("", "", 
            "a", "a", "b", 
            "a", "a", "a", "ab", "bc", "c", 
            "d", "a", "a", "a", "b", "c", 
            "d", "abd", "a", "ad", "bc", "c", 
            "d", "abd", "a", "ad", "bc", "c"),
  y_position = c(350, 350, 
                 350, 350, 350, 
                 350, 350, 350, 350, 350, 350,
                 350, 350, 350, 350, 350, 350,
                 350, 350, 350, 350, 350, 350,
                 350, 350, 350, 350, 350, 350),
  Burn = c("unburned", "burned",
           "unburned", "unburned", "burned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned"))

ggplot(mean_daily_new, aes(x = site.ID, y = dailyfDOM, pattern = Burn, fill = site.ID)) +
        ggdist::stat_halfeye(adjust = 0.5, 
                       justification = -.3,
                       .width = -0,
                       point_colour = NA,
                       scale = 0.5) +
  geom_boxplot(width = .25,
                 outlier.colour = NA,
                 alpha = 0.5) +
   geom_boxplot_pattern(position = position_dodge(preserve = "single"), 
                        width = .25,
                        color = "black", 
                        pattern_fill = "white", 
                        pattern_angle = 45, 
                        pattern_density = 0.1, 
                        pattern_spacing = 0.025, 
                        pattern_key_scale_factor = 0.6) +
  scale_pattern_manual(values = c(burned = "stripe", unburned = "none")) +
  scale_x_discrete(limits = desired_order,
                   labels = c("POKE" = "POKE\n(25%)",
                              "CARI" = "CARI\n(29%)",
                              "STRT" = "STRT\n(30%)",
                              "FRCH" = "FRCH\n(33%)",
                              "MOOS" = "MOOS\n(38%)",
                              "VAUL" = "VAUL\n(58%)")) +
  coord_cartesian(xlim = c(1, 6.05)) +
  
  scale_fill_manual(values=c("#3288BD","#FF7F00", "#E7298A", "#A6761D", "#6A3D9A", "#66C2A5"), guide = "none") +
  scale_x_discrete(limits = desired_order,
                   labels = c("POKE" = "POKE\n(25%)",
                              "CARI" = "CARI\n(29%)",
                              "STRT" = "STRT\n(30%)",
                              "FRCH" = "FRCH\n(33%)",
                              "MOOS" = "MOOS\n(38%)",
                              "VAUL" = "VAUL\n(58%)")) +
  facet_wrap(~year) +
  geom_text(data = annotations, aes(label = Label, y = y_position), 
            position = position_dodge(width = 0.75), size = 8) +
  theme_tq() +
  theme(axis.text.x = element_text(size = 16),
        axis.title.y = element_text(size = 25),
        axis.text.y = element_text(size = 20),
        strip.text = element_text(size = 20), 
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20)) +
  labs(x= "", y = "fDOM (QSU)")

ggsave("DOC_facet_year.pdf",
       path = here("plots", "Publication"),
       width = 15, height = 12)

```

```{r - SPC}
# all years  #
# POKE - 25%
# CARI - 29%
# STRT - 30%
# FRCH - 33%
# MOOS - 38%
# VAUL - 58%
desired_order <- c("POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL")

# with letters # 
annotations <- data.frame(
  year = c("2015", "2015",
           "2018", "2018", "2018", 
           "2019", "2019", "2019", "2019", "2019", "2019",
           "2020", "2020", "2020", "2020", "2020", "2020",
           "2021", "2021", "2021", "2021", "2021", "2021",
           "2022", "2022", "2022", "2022", "2022", "2022"),
  site.ID = c("FRCH", "MOOS",
              "CARI",  "FRCH", "MOOS",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL"),
  Label = c("", "", 
            "a", "a", "b", 
            "ab", "a", "ab", "a", "ab", "b", 
            "ab", "a", "ab", "a", "ab", "b", 
            "d", "b", "ad", "ab", "ad", "c", 
            "d", "b", "ad", "ab", "ad", "c"),
  y_position = c(100, 100, 
                 150, 150, 150, 
                 750, 750, 750, 750, 750, 750,
                 500, 500, 500, 500, 500, 500,
                 900, 900, 900, 900, 900, 900,
                 1000, 1000, 1000, 1000, 1000, 1000),
  Burn = c("unburned", "burned",
           "unburned", "unburned", "burned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned"))

ggplot(mean_daily_new, aes(x = site.ID, y = dailySPC, pattern = Burn, fill = site.ID)) +
        ggdist::stat_halfeye(adjust = 0.5, 
                       justification = -.3,
                       .width = -0,
                       point_colour = NA,
                       scale = 0.5) +
  geom_boxplot(width = .25,
                 outlier.colour = NA,
                 alpha = 0.5) +
   geom_boxplot_pattern(position = position_dodge(preserve = "single"), 
                        width = .25,
                        color = "black", 
                        pattern_fill = "white", 
                        pattern_angle = 45, 
                        pattern_density = 0.1, 
                        pattern_spacing = 0.025, 
                        pattern_key_scale_factor = 0.6) +
  scale_y_log10() +
  scale_pattern_manual(values = c(burned = "stripe", unburned = "none")) +
  scale_x_discrete(limits = desired_order,
                   labels = c("POKE" = "POKE\n(25%)",
                              "CARI" = "CARI\n(29%)",
                              "STRT" = "STRT\n(30%)",
                              "FRCH" = "FRCH\n(33%)",
                              "MOOS" = "MOOS\n(38%)",
                              "VAUL" = "VAUL\n(58%)")) +
  coord_cartesian(xlim = c(1, 6.05)) +
  
  scale_fill_manual(values=c("#3288BD","#FF7F00", "#E7298A", "#A6761D", "#6A3D9A", "#66C2A5"), guide = "none") +
  scale_x_discrete(limits = desired_order,
                   labels = c("POKE" = "POKE\n(25%)",
                              "CARI" = "CARI\n(29%)",
                              "STRT" = "STRT\n(30%)",
                              "FRCH" = "FRCH\n(33%)",
                              "MOOS" = "MOOS\n(38%)",
                              "VAUL" = "VAUL\n(58%)")) +
  facet_wrap(~year, scales = "free") +
  geom_text(data = annotations, aes(label = Label, y = y_position), 
            position = position_dodge(width = 0.75), size = 8) +
  theme_tq() +
  theme(axis.text.x = element_text(size = 16),
        axis.title.y = element_text(size = 25),
        axis.text.y = element_text(size = 20),
        strip.text = element_text(size = 20), 
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20)) +
  labs(x= "", y = "SPC (uS/cm)")

ggsave("SPC_facet_year.pdf",
       path = here("plots", "Publication"),
       width = 15, height = 12)

```

```{r - Turb}
# all years  #
# POKE - 25%
# CARI - 29%
# STRT - 30%
# FRCH - 33%
# MOOS - 38%
# VAUL - 58%
desired_order <- c("POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL")

# with letters # 
annotations <- data.frame(
  year = c("2015", "2015",
           "2018", "2018", "2018", 
           "2019", "2019", "2019", "2019", "2019", "2019",
           "2020", "2020", "2020", "2020", "2020", "2020",
           "2021", "2021", "2021", "2021", "2021", "2021",
           "2022", "2022", "2022", "2022", "2022", "2022"),
  site.ID = c("FRCH", "MOOS",
              "CARI",  "FRCH", "MOOS",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL"),
  Label = c("", "", 
            "", "", "", 
            "ab", "a", "ab", "b", "ab", "ab", 
            "ab", "a", "ab", "b", "ab", "ab", 
            "a", "a", "ab", "bc", "bc", "b", 
            "a", "a", "a", "a", "a", "b"),
  y_position = c(100, 100, 
                 150, 150, 150, 
                 750, 750, 750, 750, 750, 750,
                 500, 500, 500, 500, 500, 500,
                 900, 900, 900, 900, 900, 900,
                 1000, 1000, 1000, 1000, 1000, 1000),
  Burn = c("unburned", "burned",
           "unburned", "unburned", "burned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned"))

ggplot(mean_daily_new, aes(x = site.ID, y = dailyTurb, pattern = Burn, fill = site.ID)) +
        ggdist::stat_halfeye(adjust = 0.5, 
                       justification = -.3,
                       .width = -0,
                       point_colour = NA,
                       scale = 0.5) +
  geom_boxplot(width = .25,
                 outlier.colour = NA,
                 alpha = 0.5) +
   geom_boxplot_pattern(position = position_dodge(preserve = "single"), 
                        width = .25,
                        color = "black", 
                        pattern_fill = "white", 
                        pattern_angle = 45, 
                        pattern_density = 0.1, 
                        pattern_spacing = 0.025, 
                        pattern_key_scale_factor = 0.6) +
  scale_y_log10() +
  scale_pattern_manual(values = c(burned = "stripe", unburned = "none")) +
  scale_x_discrete(limits = desired_order,
                   labels = c("POKE" = "POKE\n(25%)",
                              "CARI" = "CARI\n(29%)",
                              "STRT" = "STRT\n(30%)",
                              "FRCH" = "FRCH\n(33%)",
                              "MOOS" = "MOOS\n(38%)",
                              "VAUL" = "VAUL\n(58%)")) +
  coord_cartesian(xlim = c(1, 6.05)) +
  
  scale_fill_manual(values=c("#3288BD","#FF7F00", "#E7298A", "#A6761D", "#6A3D9A", "#66C2A5"), guide = "none") +
  scale_x_discrete(limits = desired_order,
                   labels = c("POKE" = "POKE\n(25%)",
                              "CARI" = "CARI\n(29%)",
                              "STRT" = "STRT\n(30%)",
                              "FRCH" = "FRCH\n(33%)",
                              "MOOS" = "MOOS\n(38%)",
                              "VAUL" = "VAUL\n(58%)")) +
  facet_wrap(~year, scales = "free") +
  geom_text(data = annotations, aes(label = Label, y = y_position), 
            position = position_dodge(width = 0.75), size = 8) +
  theme_tq() +
  theme(axis.text.x = element_text(size = 16),
        axis.title.y = element_text(size = 25),
        axis.text.y = element_text(size = 20),
        strip.text = element_text(size = 20), 
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20)) +
  labs(x= "", y = "Turbidity (FNU)")

ggsave("Turb_facet_year.pdf",
       path = here("plots", "Publication"),
       width = 15, height = 12)

```

### storm metrics for all sites and constituents - 11_HI_Anova_models ###
```{r - load in the data }
AMC <- read.csv(here("Output_from_analysis", "07_Combine_HI_BETA_FI", "antecedent_HI_FI_AllYears.csv"))

AMC <- AMC[c("Hyst_index","site.ID", "storm.ID", "response_var", "Flush_index", "month.y", "day.y", "year", "Beta_index", "doy", "burn", "pf", "date")] # selecting the columns that I want

colNames <- c("Hyst_index", "site.ID", "storm.ID", "response_var", "Flush_index", "month", "day", "year", "Beta_index", "doy", "burn", "pf", "date")

names(AMC)<- colNames # renaming columns 

AMC <- AMC %>% 
  group_by(site.ID, response_var, year) %>% 
  dplyr::summarise(meanHI = mean(Hyst_index, na.rm = TRUE),
                   meanBETA = mean(Beta_index, na.rm = TRUE),
                   sdHI = sd(Hyst_index, na.rm = TRUE),
                   sdBETA = sd(Beta_index, na.rm = TRUE),
                   CVhi = sdHI/meanHI,
                   CVbeta = sdBETA/meanBETA,
                   response_var = paste(response_var),
                   Date = as.Date(date),
                   DOY = as.numeric(doy),
                   burn = paste(burn),
                   PF = paste(pf))

AMC <- AMC[!duplicated(AMC$meanHI), ] # removing duplicated rows 

AMC$year <- as.character(AMC$year)


AMC <- AMC %>% 
  mutate(across(c(burn),
                ~ifelse(site.ID == "CARI" | site.ID == "FRCH" | site.ID == "VAUL", "unburned", "burned")))

AMC <- AMC %>% 
  mutate(across(c(PF),
                ~ifelse(site.ID == "VAUL" | site.ID == "MOOS", "High", "Low")))


##subsetting by solute 
# NO3 #
HI_FI_NO3 = subset(AMC, response_var == "NO3")
# fDOM #
HI_FI_fDOM = subset(AMC, response_var == "fDOM")
# SPC #
HI_FI_SPC = subset(AMC, response_var == "SPC")
# turb #

AMC_new <- AMC # reordering the sites to group by burn categorization 
AMC_new$site.ID <- factor(AMC_new$site.ID,     # Reorder factor levels
                         c("CARI", "FRCH", "VAUL", "MOOS", "POKE", "STRT"))

AMC_new$Burn <- AMC_new$burn

vn = expression(paste(N*O[3]^"-"))

supp.labs <- c("fDOM","NO3-", "SPC", "Turbidity")
names(supp.labs) <- c("fDOM", "NO3", "SPC", "turb")

AMC_new <- AMC_new %>% 
  filter(response_var != "abs") 

AMC_new$facets = factor(AMC_new$response_var, labels = c(
    "fDOM",
    "NO3~^{-})",
    "SPC", 
    "Turbidity"))


my_labeller <- as_labeller(c(NO3 = "NO[3]", fDOM="fDOM", SPC="SPC", turb = "Turbidity"),
                           default = label_parsed)

my_labeller <- as_labeller(c(NO3 = expression(paste("NO"[3]^"-")), fDOM="fDOM", SPC="SPC", turb = "Turbidity"),
                           default = label_parsed)

```

### PLOTTING ####
```{r - meanHI}
# all years  #
# POKE - 25%
# CARI - 29%
# STRT - 30%
# FRCH - 33%
# MOOS - 38%
# VAUL - 58%
desired_order <- c("POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL")

annotations <- data.frame(
  response_var = c("fDOM", "fDOM","fDOM", "fDOM", "fDOM", "fDOM",
                   "NO3", "NO3","NO3", "NO3", "NO3", "NO3",
                   "SPC", "SPC","SPC", "SPC", "SPC", "SPC",
                   "turb", "turb","turb", "turb", "turb", "turb"),
  site.ID = c("POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL",
              "POKE", "CARI", "STRT", "FRCH", "MOOS", "VAUL"),
  Label = c("c", "c", "bc", "bc", "ab", "a",  # fDOM
            "", "", "", "", "", "",  # NO3
            "", "", "", "", "", "",  # SPC
            "", "", "", "", "", ""  # Turb
            ),
  y_position = c(0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 
                 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 
                 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 
                 0.5, 0.5, 0.5, 0.5, 0.5, 0.5),
  Burn = c("burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned",
           "burned", "unburned", "burned", "unburned", "burned", "unburned"))

ggplot(AMC_new, aes(x = site.ID, y = meanHI, pattern = Burn, fill = site.ID)) +
        ggdist::stat_halfeye(adjust = 0.5, 
                       justification = -.3,
                       .width = -0,
                       point_colour = NA,
                       scale = 0.5) +
  geom_boxplot(width = .25,
                 outlier.colour = NA,
                 alpha = 0.5) +
  geom_boxplot_pattern(position = position_dodge(preserve = "single"), 
                        width = .25,
                        color = "black", 
                        pattern_fill = "white", 
                        pattern_angle = 45, 
                        pattern_density = 0.1, 
                        pattern_spacing = 0.025, 
                        pattern_key_scale_factor = 0.6) +
  geom_hline(yintercept= 0, linetype="dashed", color = "red") +
  scale_pattern_manual(values = c(burned = "stripe", unburned = "none")) +
  scale_x_discrete(limits = desired_order,
                   labels = c("POKE" = "POKE\n(25%)",
                              "CARI" = "CARI\n(29%)",
                              "STRT" = "STRT\n(30%)",
                              "FRCH" = "FRCH\n(33%)",
                              "MOOS" = "MOOS\n(38%)",
                              "VAUL" = "VAUL\n(58%)")) +
  coord_cartesian(xlim = c(1, 6.05)) +
  scale_fill_manual(values=c("#3288BD","#FF7F00", "#E7298A", "#A6761D", "#6A3D9A", "#66C2A5"), guide = "none") +
  xlab("") +
  ylab("Mean HI") +
  theme_tq() +
  geom_text(data = annotations, aes(label = Label, y = y_position), 
            position = position_dodge(width = 0.75), size = 8) +
  facet_wrap(~response_var, labeller = my_labeller) +
  theme(axis.text.x=element_text(size=18), 
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.position = "bottom",
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20),
        strip.text = element_text(size = 20)) 

ggsave("mean_HI_facet_constituent.pdf",
       path = here("plots", "Publication"),
       width = 10, height = 10)
```



### Graveyard code ####
```{r code graveyard}
# Install and load the ggplot2 package if you haven't already
# install.packages("ggplot2")
library(ggplot2)

# Create a sample dataset
data <- data.frame(
  x = rnorm(100),
  y = rnorm(100),
  facet_var = rep(c("Group 1", "Group 2"), each = 50)
)

# Create a ggplot with facets and superscript in facet labels
ggplot(data, aes(x, y)) +
  geom_point() +
  facet_wrap(~facet_var, labeller = label_parsed) +
  labs(
    title = "Scatter plot with Facets",
    x = "X-axis",
    y = "Y-axis",
    caption = "Source: Your Data Source"
  )


# Jacob code #
# ggplot(mean_daily_new, aes(x = interaction(PF, Burn), y = dailyNO3)) +
#   geom_boxplot(aes(fill = PF), alpha = 0.7, outlier.shape = NA) +
#   scale_fill_discrete(name = "Permafrost Extent") +
#   scale_fill_manual(values = c("grey","white"),name = "Permafrost Extent") +
#   # scale_fill_discrete() +
#   new_scale_fill() +
#   geom_point(aes(fill = interaction(PF,site.ID)), shape = 21,
#              position = position_jitterdodge(dodge.width = 0.5), size = 3) +
#   scale_fill_manual(values = c("#3288BD","#FF7F00", "#E7298A", "#A6761D", "#6A3D9A", "#66C2A5"), labels = c("Caribou", "French", "Vault", "Moose","Poker", "Stuart"), name = "Stream Site") +
#   labs(x= "", y = vn) +
#   facet_wrap(.~year) +
#   theme(axis.text.x = element_blank(),
#         axis.ticks.x = element_blank(),
#         panel.spacing.x = unit(0, "lines"),
#         strip.background = element_rect(fill = "transparent")) +
#   theme(panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         panel.background = element_blank(),
#         panel.border = element_rect(colour = "black", fill=NA, size=2))+theme(aspect.ratio = 1) +
#   theme(legend.title = element_text(size=15),legend.text = element_text(size=15)) + theme(
#           axis.text = element_text(size = 15),    
#           axis.title = element_text(size = 15),
#           strip.text = element_text(size = 15))
# 
# ggsave("NO3_facet_year.pdf",
#        path = here("plots", "Publication"),
#        width = 10, height = 10)
# 
# # 
# # Another take on the above code but
# ggplot(mean_daily_new, aes(x = site.ID, y = dailyNO3, pattern = PF, fill = site.ID)) +
#    geom_boxplot() +
#    geom_boxplot_pattern(position = position_dodge(preserve = "single"), color = "black", pattern_fill = "white", pattern_angle = 45, pattern_density = 0.1, pattern_spacing = 0.025, pattern_key_scale_factor = 0.6) +
#   scale_pattern_manual(values = c(High = "stripe", Moderate = "none")) +
#   scale_fill_manual(values=c("#3288BD","#FF7F00", "#E7298A", "#A6761D", "#6A3D9A", "#66C2A5"), guide = "none") +
#   new_scale_fill() +
#    geom_boxplot(aes(fill = Burn), alpha = 0.5, outlier.shape = NA) +
#    scale_fill_manual(values = c("black","white"),name = "Burn") +
#    labs(x= "", y = vn) +
#   facet_wrap(.~year) +
#   theme(axis.text.x=element_text(size=20, angle = 90, vjust = 0.5, hjust=1),
#         axis.ticks.x = element_blank(),
#         panel.spacing.x = unit(0, "lines"),
#         strip.background = element_rect(fill = "transparent")) +
#   theme(panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         panel.background = element_blank(),
#         panel.border = element_rect(colour = "black", fill=NA, size=2))+theme(aspect.ratio = 1) +
#   theme(legend.title = element_text(size=15),legend.text = element_text(size=15)) + theme(
#           axis.text = element_text(size = 15),    
#           axis.title = element_text(size = 15),
#           strip.text = element_text(size = 15))
#   
# ggsave("NO3_facet_year_2.pdf",
#        path = here("plots", "Publication"),
#        width = 10, height = 10)
# 
# 
# # boxplots with density plots
# ggplot(mean_daily_new, aes(x = site.ID, y = dailyNO3, fill = site.ID)) +
#    ggdist::stat_halfeye(adjust = 0.5, 
#                        justification = -.2,
#                        .width = 0,
#                        point_colour = NA) +
#   geom_boxplot(width = .25,
#                  outlier.colour = NA,
#                  alpha = 0.5) +
#   ggdist::stat_dots(side = "left",
#                     justification = 1.1, 
#                     binwidth = 0.25) +
#   facet_wrap(~year) +
#   theme_classic()
#     
# ggsave("NO3_facet_year_density.pdf",
#        path = here("plots", "Publication"),
#        width = 10, height = 10)
# 
# 
# ### Chat GPT code for letters of statistical significance ###
# # Install and load necessary packages
# # Generate some example data
# set.seed(123)
# data <- data.frame(
#   Group = rep(c("A", "B", "C"), each = 30),
#   Value = c(rnorm(30), rnorm(30, mean = 1), rnorm(30, mean = 2))
# )
# 
# # Create a boxplot
# p <- ggplot(data, aes(x = Group, y = Value)) +
#   geom_boxplot()
# 
# # Add significance letters
# p + geom_signif(comparisons = list(c("A", "B"), c("B", "C"), c("A", "C")),
#                 map_signif_level = TRUE)
#    
# 
# 
# ### lets try and build out of the code with levels of significance for an individual year 
# # 2015
# chem_2015 <- mean_daily_new %>% 
#   filter(year == "2015")
# 
# chem_2015$site.ID <- factor(chem_2015$site.ID)
# 
# ggplot(chem_2015, aes(x = site.ID, y = dailyNO3)) +
#   geom_boxplot() + 
#   geom_signif(comparisons = list(c("FRCH", "MOOS")), 
#               map_signif_level = TRUE)
# 
# # 2018
# chem_2018 <- mean_daily_new %>% 
#   filter(year == "2018")
# 
# ggplot(chem_2018, aes(x = site.ID, y = dailyNO3)) +
#   geom_boxplot() + 
#   geom_signif(comparisons = list(c("CARI", "FRCH"), c("FRCH", "MOOS"), c("CARI", "MOOS")), 
#               map_signif_level = TRUE,
#                 step_increase = 0.2)
# 
# # 2015 and 2018
# chem_2015_2018 <- rbind(chem_2015, chem_2018)
# 
# ggplot(chem_2015_2018, aes(x = site.ID, y = dailyNO3, fill = site.ID)) +
#   geom_boxplot() + 
#   scale_fill_manual(values=c("#FF7F00", "#A6761D", "#3288BD"), guide = "none") +
#   geom_signif(comparisons = list(c("CARI", "FRCH"), c("FRCH", "MOOS"), c("CARI", "MOOS")), 
#               map_signif_level = TRUE,
#                 step_increase = 0.2) +
#   facet_wrap(~year) +
#   theme_bw() +
#   theme(legend.position = "none") +
#   labs(x= "", y = vn) 
#   
# ggsave("NO3_facet_year_1.pdf",
#        path = here("plots", "Publication"),
#        width = 10, height = 10)
# 
# # with hatch for WF #
# ggplot(chem_2015_2018, aes(x = site.ID, y = dailyNO3, pattern = Burn, fill = site.ID)) +
#   ggdist::stat_halfeye(adjust = 0.5, 
#                        justification = -.2,
#                        .width = -0,
#                        point_colour = NA,
#                        scale = 0.5) +
#    geom_boxplot(width = .25,
#                  outlier.colour = NA,
#                  alpha = 0.5) +
#    geom_boxplot_pattern(position = position_dodge(preserve = "single"), 
#                         width = .25,
#                         color = "black", 
#                         pattern_fill = "white", 
#                         pattern_angle = 45, 
#                         pattern_density = 0.1, 
#                         pattern_spacing = 0.025, 
#                         pattern_key_scale_factor = 0.6) +
#   scale_pattern_manual(values = c(burned = "stripe", unburned = "none")) +
#   scale_fill_manual(values=c("#FF7F00", "#A6761D", "#3288BD"), guide = "none") +
#   geom_signif(comparisons = list(c("CARI", "FRCH"), c("FRCH", "MOOS"), c("CARI", "MOOS")), 
#               map_signif_level = TRUE,
#               step_increase = 0.2) +
#   scale_x_discrete(labels = c("FRCH" = "FRCH\n(33%)",
#                               "MOOS" = "MOOS\n(38%)",
#                               "CARI" = "CARI\n(29%)")) +
#                               
#   facet_wrap(~year) +
#   theme_tq() +
#   labs(x= "", y = vn) 
#   
# ggsave("NO3_facet_year_1.pdf",
#        path = here("plots", "Publication"),
#        width = 10, height = 10)


```



